### ISSUE TITLE
Feedback features should be more interactive

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#101]
@abuxton suggests that 
1. A presenter should be able to mark off questions as answered
2. When an audience member asks a question, they should have a visual indication that their question exists in the queue and should be notified when the presenter marks it as answered.

**Comment by binford2k** [comment]
Part 1 of this is done.

**Comment by marrero984** [comment]
Related to this, marking a question as answered should require more than just clicking on the question.  It is an issue when questions stack up and the presenter accidentally clicks on a question while trying to scroll in the small question window

**Comment by binford2k** [comment]
a checkbox maybe? They don't have to disappear.
