### ISSUE TITLE
Slides with bullets incremental can´t be shown via /presenter

### ISSUE THREAD

**Issue by ghost** [binford2k/showoff#132]
I create a presentation named Foo

```
showoff create Foo
```

cd into the directory and start showoff

```
cd Foo
showoff serve
```

I didn`t touch anything in the default slide.

```
!SLIDE 
# My Presentation #

!SLIDE bullets incremental
# Bullet Points #

* first point
* second point
* third point
```

Now i open a presenter on localhost:9090/presenter.
It opens with the Slide "My Presentation". After pressing SPACE and advancing to the next slide "Bullet points" pressing SPACE doesn´t work anymore. I can´t show the bulletpoints.

Even if i insert a slide after the "Bulltetpoint" slide, it does not advance.
I tried this on Mac OSX 10.9.2 with Firefox, Safari and Chrome. 

Opening localhost:9090 (without presenter) shows everything as expected and incremental bulletpoints do work. 

Opening localhost:9090 (as follower of a presenter) does not work in this context, because the presenter stucks.

Opening the presenter and a slave window also is woking odd. I can navigate the slave window, it does change the presenter and followers, but if the slave window shows bullets incremental, these are neither shown in the presenter nor in the following windows. After all bullets are shown and the slave advances to a new slide, this slide is shown in the presenter and the followers.

Is there anything I can do, to get the presenter working correct ?

**Comment by donv** [comment]
I am having the same problem now.  @tobollam did you find a solution?
