### ISSUE TITLE
Images not resizing?

### ISSUE THREAD

**Issue by jeffrabovsky** [binford2k/showoff#154]
I have a slide that looks like this:

```
!SLIDE center
![Schematic](http://arduino.cc/en/uploads/Main/ArduinoSeverinoSchematic.png)
```

I'm using showoff 0.9.8.1 and rmagick 2.13.2 and my image ends up mostly off the slide. Any ideas what's going on here?

Thanks!

**Comment by slambert** [comment]
If you can upload a screenshot, I could get a better idea but try:

`!SLIDE full-page
![Schematic](http://arduino.cc/en/uploads/Main/ArduinoSeverinoSchematic.png)`

or 
`!SLIDE background-fit
![Schematic](http://arduino.cc/en/uploads/Main/ArduinoSeverinoSchematic.png)`

**Comment by marrero984** [comment]
Images larger than the slide are now scaled down by CSS.  See #280
