### ISSUE TITLE
Support CommonMark

### ISSUE THREAD

**Issue by raphink** [binford2k/showoff#177]
Now that Mardown has a ~~standard~~ fork that most main users seem to agree on, it would be great if showoff would support it: http://commonmark.org/

**Comment by raphink** [comment]
https://github.com/jgm/commonmarker ?

**Comment by raphink** [comment]
or rather https://github.com/gjtorikian/commonmarker/ now

**Comment by raphink** [comment]
@binford2k Just opened https://github.com/rtomayko/tilt/pull/281 as a first step

**Comment by raphink** [comment]
Working version at https://github.com/raphink/showoff/tree/commonmark, I'll open a PR to discuss it.

**Comment by binford2k** [comment]
Fixed in #482
