### ISSUE TITLE
redcarpet used in non-threadsafe way

### ISSUE THREAD

**Issue by llowder** [binford2k/showoff#219]
While running the example show, noticed the following warning in the logs:

> WARN: tilt autoloading 'redcarpet' in a non thread-safe way; explicit require 'redcarpet' suggested.

**Comment by binford2k** [comment]
that's been around forever. It's due to dynamically loading an engine on demand. Should not be a problem, because we're not threading anyway. But I might fix it one of these days.

**Comment by llowder** [comment]
Since it's probably an easy fix, I'll try to do s PR once I finish testing the one I am working on.

**Comment by binford2k** [comment]
Fixed in #482
