### ISSUE TITLE
progress tracking appears to be crashing sometimes

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#237]
We should at least catch this, and preferably clean up how the tracking works.

```
10.0.28.22 - - [20/Mar/2015 11:01:30] "GET /control HTTP/1.1" -1 - 14.9493
Stopping ...
== Sinatra has ended his set (crowd applauds)
error: can't add a new key into hash during iteration
```

**Comment by binford2k** [comment]
192.168.103.8 - - [07/Apr/2015 16:04:08] "GET /image/_images/pe-console-class-parameters.png HTTP/1.1" 304 - 0.0006
 websocket closed
127.0.0.1 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 24721.0996
 websocket closed
192.168.103.127 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 24480.3046
 websocket closed
127.0.0.1 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 21547.7451
 websocket closed
192.168.103.11 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 13855.5689
 websocket closed
192.168.103.7 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 10169.7195
 websocket closed
192.168.103.14 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 9154.8630
 websocket closed
192.168.103.4 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 3259.0096
 websocket closed
192.168.103.8 - - [07/Apr/2015 16:04:08] "GET /control HTTP/1.1" -1 - 5.1856
Stopping ...
== Sinatra has ended his set (crowd applauds)
error: can't add a new key into hash during iteration

**Comment by binford2k** [comment]
Gem list from @LMacchi who's seeing the problem occasionally

```
lmacchi@Titere:~ > gem list

*** LOCAL GEMS ***

activesupport (4.2.1, 4.2.0)
addressable (2.3.8, 2.3.6)
archive-tar-minitar (0.5.2)
autoparse (0.3.3)
aws-s3 (0.6.3)
aws-sdk (1.60.2)
aws-sdk-v1 (1.60.2)
beaker (2.1.0)
beaker-rspec (4.0.0)
bigdecimal (1.2.0)
blankslate (3.1.3, 2.1.2.4)
builder (3.2.2)
bundle (0.0.1)
bundler (1.9.9, 1.8.1, 1.7.11)
CFPropertyList (2.3.1, 2.2.8)
css_parser (1.3.6)
daemons (1.1.9)
diff-lcs (1.2.5)
docker-api (1.17.0)
em-websocket (0.3.8)
eventmachine (1.0.7, 1.0.4, 1.0.3)
excon (0.42.1)
extlib (0.9.16)
facter (2.4.1 universal-darwin)
faraday (0.9.1, 0.9.0)
fission (0.5.0)
fog (1.26.0)
fog-atmos (0.1.0)
fog-brightbox (0.7.1)
fog-core (1.27.2)
fog-ecloud (0.0.2)
fog-json (1.0.0)
fog-profitbricks (0.0.1)
fog-radosgw (0.0.3)
fog-sakuracloud (0.1.1)
fog-softlayer (0.3.26)
fog-storm_on_demand (0.1.0)
fog-terremark (0.0.3)
fog-vmfusion (0.0.1)
fog-voxel (0.0.2)
fog-xml (0.1.1)
formatador (0.2.5)
github-markup (1.3.3)
gli (2.12.2, 2.12.1)
google-api-client (0.8.1.1)
hiera (1.3.4)
highline (1.6.21)
hocon (0.0.6)
htmlentities (4.3.3, 4.3.2)
i18n (0.7.0)
inflecto (0.0.2)
inifile (2.0.2)
io-console (0.4.2)
ipaddress (0.8.0)
jmespath (1.0.2)
json (1.8.1, 1.7.7)
json_pure (1.8.2)
jwt (1.2.0)
launchy (2.4.3)
libxml-ruby (2.6.0)
log4r (1.1.10)
micromachine (1.1.0)
mime-types (2.4.3)
mini_portile (0.6.2)
minitest (5.5.0, 4.3.2)
multi_json (1.10.1)
multipart-post (2.0.0)
net-scp (1.2.1)
net-ssh (2.9.1)
nokogiri (1.6.6.2, 1.5.6)
parslet (1.6.2, 1.6.1)
pdfkit (0.6.2)
premailer (1.8.4)
psych (2.0.0)
puppet (3.7.4)
puppet-lint (1.1.0)
rack (1.6.0, 1.5.2)
rack-protection (1.5.3)
rake (10.4.2, 0.9.6)
rbvmomi (1.8.2)
rdoc (4.0.0)
redcarpet (3.2.3, 3.2.2, 3.1.2)
retriable (1.4.1)
rouge (1.8.0)
rspec (2.99.0)
rspec-core (2.99.2)
rspec-expectations (2.99.2)
rspec-its (1.0.1)
rspec-mocks (2.99.2)
rspec-puppet (2.0.1)
rubygems-update (2.4.1)
serverspec (1.16.0)
showoff (0.9.11.1, 0.9.10.8, 0.9.10.7, 0.9.10.3, 0.9.10.1, 0.9.10, 0.9.9.1)
signet (0.6.0)
sinatra (1.4.5)
sinatra-websocket (0.3.1, 0.3.0)
specinfra (1.27.5)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
thin (1.6.3, 1.6.2)
thread_safe (0.3.4)
tilt (1.4.1)
trollop (2.1.1)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.6)
vagrant-vbguest (0.10.0)
vagrant-wrapper (2.0.1)
wkhtmltopdf (0.1.2)
wkhtmltopdf-binary (0.9.9.3)
xml-simple (1.1.4)
```

Unfortunately, even with these gems, I'm unable to replicate this. I've had a server running for days with 3 clients. I'm going to have to punt again until we can make this more reproducible. :(

@LMacchi & @pizzaops please add info if/when you see this again.

(That said, the fact that the server actually crashes makes it likely that this is a Rack bug, as Showoff errors should actually only kill that thread and not the whole server.)

**Comment by big-samantha** [comment]
I haven't had any issues during my current fundamentals, btw. It might have
been a fluke.

**Comment by LMacchi** [comment]
Same for me, starting day 3 and no crashes.
