### ISSUE TITLE
Blank screen doesn't stay blank

### ISSUE THREAD

**Issue by slambert** [binford2k/showoff#243]
1. run a slideshow
2. open http://localhost:9090/ in browser
3. hit 'b'

Slide moves down, then re-appears.

Tried in Firefox and Safari with a slideshow I created and the /example slideshow in the showoff git repo.

**Comment by binford2k** [comment]
Bah. Workaround is to drop these styles in your presentation. Fix upcoming. Thanks again!

``` css
html, body{
  height:100%;
}
```
