### ISSUE TITLE
Next Window doesn't resize in Firefox

### ISSUE THREAD

**Issue by slambert** [binford2k/showoff#244]
The slide view in Next Window doesn't scale to fit the window in Firefox. 

I tried some relative font size tricks from responsive css, but not sure what the best, universal solution is.

**Comment by marrero984** [comment]
Looks like a JS problem.  In Chrome and Safari, when the window is resized, setupPreso is called, which includes a call to a function that sets the zoom css property.  It is not being called in Firefox 37.0.1 or later; cannot check earlier versions.

**Comment by binford2k** [comment]
@marrero984 did this get addressed in #303 ?

**Comment by marrero984** [comment]
Yes, but we removed #303 shortly after because of unexpected side effects

**Comment by binford2k** [comment]
fixed
