### ISSUE TITLE
Style switching not switching

### ISSUE THREAD

**Issue by slambert** [binford2k/showoff#249]
I added another style sheet to the example slideshow included in the repo. It's identical to the `something.css` file, except I changed the color of the h1 from blue to red and named it `somethingelse.css`.

```
/* custom css and js files included at the top level of your presentation will
 * will be included in your presentation */

.title-slide h1 {
  color: red;
}
```

I served the example slideshow and the two stylesheets show up to select from, but they do not change. It uses the one that is alphabetically at the bottom of the list.

**Comment by marrero984** [comment]
This functionality has been removed with #272.  It is still possible to provide overriding CSS, but not to switch between styles from within a presentation.
