### ISSUE TITLE
Slide background images have to be saved in the root directory

### ISSUE THREAD

**Issue by alimi** [binford2k/showoff#271]
When you set a a background image for a slide (`!SLIDE[bg=an_image.png`), the image has to be in the root directory. I did not expect this behavior because slide images are in the same directory as their slide. I'm not sure if it's the intended behavior for the different types of slide images to behave differently, but it's really confusing. I didn't see any mention of it in the documentation.

This also has other unintended consequences. For example, `showoff github` doesn't copy images from the root directory so background images won't be copied over.

It looks like [this line in Showoff#process_markdown](https://github.com/puppetlabs/showoff/blob/08193c0e34b7e65529a7d82e4aafeb8c3aa4113a/lib/showoff.rb#L311) is what forces background images to be in the root directory.

Is this an issue or the intended behavior?

**Comment by binford2k** [comment]
The images don't have to live in the root directory, but the path to them starts from root. For example, if your slide was in the `demo` directory and the `bg.png` image was in the same directory, it should use a tag like `<!SLIDE[bg=demo/bg.png>`. I'll update the documentation to clarify this.

Not copying images from the root is a bug though. Thanks for letting me know.

**Comment by alimi** [comment]
Gotcha. It's super confusing because all other slide images are referenced from their slide's directory. It took me a really long time to figure out what was going on. It feels _weird_, but if that's how it works...that's how it works :grin:. I'll try to send a PR to update the documentation if I can get to it this weekend.

Should I add another issues for root images not being copied over in `showoff github`?
