### ISSUE TITLE
!SLIDE execute

### ISSUE THREAD

**Issue by hemanth** [binford2k/showoff#324]
```
# Executable JavaScript #

    @@@ javascript
    result = 3 + 3;

!SLIDE execute
```

On pressing `x` or `f5` the code doesn't execute, missing something?

**Comment by binford2k** [comment]
You'll want it to look like this:

```
!SLIDE

    @@@ javascript execute
    result = 3 + 3;
```

Each code example needs to be flagged as executable.  I apologize for the docs not being as clear as they could be.
