### ISSUE TITLE
Google Chrome left navigation menu no scroll bar

### ISSUE THREAD

**Issue by josephoaks** [binford2k/showoff#329]
Upon loading up the presenter page within chrome, there is no scroll bar in the left navigation window. As the presenter advances you are unable to see previous slides. Tested and works in both Safari and Firefox. Tested in Chrome version 44.x.x.x (64bit) and latests Chrome Version 45.0.2454.101 (64-bit) and it does not.

As I am working through this at home and it works in Safari and Firefox we can wait till after PuppetConf to look into this.

**Comment by josephoaks** [comment]
Closing ticket, seems issue was caused by browser plugin from google.

**Comment by binford2k** [comment]
Which plugin was it?

**Comment by josephoaks** [comment]
High Contrast by Google Accessibility
