### ISSUE TITLE
Image integration with `img` needs certain order of options

### ISSUE THREAD

**Issue by widhalmt** [binford2k/showoff#350]
Hi,

When I integrate an image with `<img />` tags, the `src=` option has to be the first one. Otherwise the presentation just shows the broken link icon instead of an Image.

This works:

```
<img src="../_images/indexpattern.png" style="max-width: 800px; width: auto; height: auto;" alt="" />
```

this doesn't:

```
<img style="max-width: 800px; width: auto; height: auto;" src="../_images/indexpattern.png" alt="" />
```

Maybe it is enough to add it as "known issue" to the documentation but supporting an arbitrary order would be much nicer.

I use version: 0.9.10.7

Thanks in advance,
Thomas

**Comment by binford2k** [comment]
This does not seem to be the case for me. Can you test again, and provide more context? Can you share a slide that exhibits this behavior?

**Comment by widhalmt** [comment]
I tested this with several slides. We have a heavily customised `.css` and Template file. Maybe the issue lies therin.

Here is a Slide where I saw this happen more than once:

```
!SLIDE smbullets
# Kibana 4

* Kibana needs to know where to find your events: Index pattern
* You can define more than one index pattern

<center><img src="../_images/indexpattern.png" style="max-width: 800px; width: auto; height: auto;" alt="" /></center>

~~~SECTION:notes~~~

**IMPORTANT** Sometimes the index pattern get's replicated via Elasticsearch from trainee to     trainee. Be sure nobody adds extra index patterns or at least delete them. Choosing the index     pattern for Discover and Visualisations is a pain in the bottom. It's easily done but also easily     overlooked.

~~~ENDSECTION~~~
```

I'll have to ask for permission for shareing the template and css with you.

**Comment by binford2k** [comment]
Huh. Interesting. I've validated that this slide exhibits the bug. I will investigate further and correct it. Thanks for bringing this to my attention :/

**Comment by widhalmt** [comment]
Thanks for the fast response. If I can be of any further help, just let me know.
