### ISSUE TITLE
Resizing the browser window resets progress made in a survey

### ISSUE THREAD

**Issue by carthik** [binford2k/showoff#351]
If you resize the browser window during a quiz/survey, then you lose progress, as in, your previous answers or choices are reset.

**Comment by binford2k** [comment]
This is because the slide transition plugin we use sets explicit sizes, so we reload the page to force the recalculation. @marrero984 is working on replacing it.

**Comment by carthik** [comment]
Thanks!

**Comment by binford2k** [comment]
fixed
