### ISSUE TITLE
FILE: can only be used once

### ISSUE THREAD

**Issue by widhalmt** [binford2k/showoff#356]
Hi!

I'm trying to create some slides where a code snippet, the input to it and the output from it is shown. I actually run the code snippet on the command line to create a current version of the output and have a test of the code snippet every time I change the presentation. Therefore the code, the input and the output have to be included by ~~~FILE:~~~

Every file consists only of 1-3 lines. When I use ~~~FILE:~~~ more than once in one slide, the presentation only shows an empty window.

Is this a bug or a known issue? If it's a bug, could you fix it?

Kind regards,
Thomas

**Comment by binford2k** [comment]
Hmm. Can you share the contents of a slide file? It seems to work here:

```
<!SLIDE>
# Course Overview
## You will:

#### Example file: `wrappers/examples/epel.pp`

~~~FILE:wrappers/examples/epel.pp:Puppet~~~

#### Example file: `wrappers/manifests/epel.pp`

~~~FILE:wrappers/manifests/epel.pp:Puppet~~~
```

![screen shot 2015-12-08 at 8 22 49 am](https://cloud.githubusercontent.com/assets/1392917/11661081/ebe7c8a0-9d84-11e5-8965-9504e5ff453c.png)

**Comment by widhalmt** [comment]
Of course

```
!SLIDE smaller
# kv

The `kv` filter splits strings of key-value pairs into fields

~~~FILE:../_files/kv-example~~~

It uses the following input

~~~FILE:../_files/kv-example.input~~~

to create the following output

~~~FILE:../_files/kv-example.output~~~
```

The files:

kv-example

```
filter {
  kv {
    source => "message" # the default value
  }
}
```

kv-example-input

```
ip=192.168.12.24 username=icinga
```

kv-example-output

```
{
       "message" => "ip=192.168.12.24 username=icinga",
      "@version" => "1",
    "@timestamp" => "2015-12-08T16:30:12.913Z",
          "host" => "fenris.int.netways.de",
            "ip" => "192.168.12.24",
      "username" => "icinga"
}
```

**Comment by binford2k** [comment]
What showoff version? I cannot seem to reproduce.

btw, the FILE tag is rooted in `_files`, so you can use `~~~FILE:kv-example~~~`

**Comment by widhalmt** [comment]
0.9.10.7

Thanks for the hint!

**Comment by binford2k** [comment]
coming back to this, I suspect that it was two FILE blocks one after another. That will break, because markdown doesn't have a way of delineating indented code blocks, without a block level element between. If you put text between them, the problem should go away. We've got a `.break` tag just for that, if you don't want space between them.

It would look something like:

```
<!SLIDE>
# Course Overview
## You will:

Examples:

~~~FILE:wrappers/examples/epel.pp:Puppet~~~

.break

~~~FILE:wrappers/manifests/epel.pp:Puppet~~~
```
