### ISSUE TITLE
Put a PDF version into static

### ISSUE THREAD

**Issue by bogdan** [binford2k/showoff#395]
Or at least have a command showoff pdf
Why you can't put a pdf version into static? It is a pain to generate it manually from launched server and save it manually.

**Comment by binford2k** [comment]
This is now implemented :)

**Comment by bogdan** [comment]
Which one of the options?

**Comment by binford2k** [comment]
https://github.com/puppetlabs/showoff/blob/master/documentation/USAGE.rdoc#showoff-pdf-name
