### ISSUE TITLE
List and code highlighting not working together

### ISSUE THREAD

**Issue by yila** [binford2k/showoff#397]
When I add a code snipped after a bullet:
- bullet with stuff[2 spaces]
  [new line, 4 spaces]@@@Java
  public class MyClass{
      public void doSomething(){
          //code goes here
      }
  }
- second bullet

The code looks like part of the list:
- [8 spaces]        bullet with stuff
  [new line, 4 spaces]    @@@java public class MyStack { public bool IsEmpty() { return false; } }
- [4 spaces]     second bullet

How do I get this to work?

**Comment by binford2k** [comment]
Hey @yila, that's a markdown limitation. According to the spec, you need a block level element after a list to end that list. The practical implementation of that is that you'll need to put _something_ in between.

Something like this:
- bullet with stuff[2 spaces]

blah blah blah blah

```
@@@Java
public class MyClass{
    public void doSomething(){
        //code goes here
    }
}
```
- second bullet

What I'm doing in my presentations (and what I'll probably migrate to Showoff core soon) is adding a special paragraph style to make an empty & invisible element to break the list.

```
p.break {
    display: none;
}
```

You'd use that by using a line of `.break` where I put "blah blah blah" above.

The other practical implication is that you can't really do numbered lists with embedded code unless you write the html yourself. bummer :-/

**Comment by yila** [comment]
Thanks @binford2k.  I didn't quite understand the block element part, but after you explained it, it makes sense.

Instead of adding css style, I simply added a line break tag (br-tag) where you had "blah blah blah".  And it worked!
- bullet with stuff [no spaces, just new line]

[br-tag]

```
@@@Java
public class MyClass{
    public void doSomething(){
        //code goes here
    }
}
```

Notice the spaces in between lines.  That is important as well.

Now, what I do not know is that if this is the right thing to do?  Getting it to work is one thing, but if it is not the right thing to do than I'd rather not.  Any comments on whether it is the correct way or not?

**Comment by binford2k** [comment]
Totally works. The only drawback to the br is that it takes up space. If you don't mind that, then you're good. If you want the space to go away, style it with a p tag like I suggested.

**Comment by yila** [comment]
Thanks again.  One more thing.

I read [Daring Fireball](https://daringfireball.net/projects/markdown/syntax) more closely (instead of skimming) about adding code block to list.  It says (copied directly from the website):

To put a code block within a list item, the code block needs to be indented twice — 8 spaces or two tabs:
-   A list item with a code block:
  
  ```
  <code goes here>
  ```

I did this and it worked great as far as the spacing between the bullet and the code block is concerned, but the bullet's text itself is indented.  Here is the screenshot:

<img width="1025" alt="screen shot 2016-03-03 at 10 37 19 am" src="https://cloud.githubusercontent.com/assets/2798869/13501525/a6f49fc0-e12c-11e5-9f82-53aec01b5427.png">

Any ideas/suggestion of getting around this?

**Comment by binford2k** [comment]
You know that you can drop a stylesheet into your presentation and style anything any way you want, right? https://github.com/puppetlabs/showoff/blob/master/documentation/AUTHORING.rdoc#custom-stylesheets

In any case, that looks like it might be a styling bug. Can you file a new ticket with that screenshot?

**Comment by yila** [comment]
Sure - on it - thanks again!
