### ISSUE TITLE
Code Block within a List - Bullet Text Spacing (Styling) Issue

### ISSUE THREAD

**Issue by yila** [binford2k/showoff#400]
Per conversation with @binford2k regarding [closed ticket #397](https://github.com/puppetlabs/showoff/issues/397) putting in a new bug.

I followed instructions on  [Daring Fireball](https://daringfireball.net/projects/markdown/syntax) about using code block within list.  This is what I am getting:
<img width="1001" alt="screen shot 2016-03-03 at 11 06 53 am" src="https://cloud.githubusercontent.com/assets/2798869/13502322/1ed082c2-e130-11e5-8b24-19a52ef5c7c0.png">

The code block seems fine, however, the space in front of the bulleted text is not correct.

Thanks.

**Comment by marrero984** [comment]
@yila Is this still an issue for you with the new styling released in 0.12.0?

**Comment by yila** [comment]
It's been a while since I last worked on showoff, but I think I I got around it    I haven't tried the new version so I don't know if it is still an issue.

**Comment by binford2k** [comment]
Thanks, @yila. Go ahead and reopen this if you still see the issue!
