### ISSUE TITLE
paragraph styles

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#410]
Add some paragraph styles with FA icons as appropriate. Feel free to alter the list. The only ones required are the `info` & `callout` classes and the left/right floats.
- `info`
- `callout`
- `reminder`
- `warning`
- `history` (like a historical note, something like "this looks weird, but it's here because we used to...")
- `activity`
- `call-to-action` ? maybe

Also add a `left` and a `right` float for images and paragraphs.

**Comment by marrero984** [comment]
Callouts added by https://github.com/puppetlabs/showoff/pull/412
