### ISSUE TITLE
Have to restart server to see a slide update

### ISSUE THREAD

**Issue by nathanl** [binford2k/showoff#534]
I'm running showoff `0.13.1` and viewing my slides in Chrome 51, with the developer console open and "Disable cache" checked.

When I edit a slide, save it, and refresh the browser, I don't see the updated content. I have to stop the server and restart it to see the change.

Is that expected, or am I doing something wrong?

**Comment by marrero984** [comment]
Hi @nathanl 
If you hit 'r' on the slides, it will reload the slide content from the server with any updates you have made.

**Comment by nathanl** [comment]
Yes, that works! Thanks! 😄

**Comment by nathanl** [comment]
@marrero984 I notice that this mechanism does not reload my custom CSS file; for that, I have to use a normal browser refresh.

Not sure if it's worth creating another issue, but I find that confusing. IMO it would be best if a browser refresh reloaded everything, as it does for any other web page.

**Comment by binford2k** [comment]
@nathanl imagine presenting to an audience of 50 and they're all following along in their browsers. That would mean concurrently compiling the presentation 50 times as they all loaded it. Caching the compiled presentation boosts performance by ridiculous amounts, that isn't going to change.

You _could_ file a ticket to add a browser refresh to the `reload` function. That seems like a reasonable thing to do.

**Comment by nathanl** [comment]
> imagine presenting to an audience of 50 and they're all following along in their bromwsers. That would mean concurrently compiling the presentation 50 times as they all loaded it.

Good point. I guess I imagined this in a "development mode". But in any case, thanks for the quick PR! Problem solved!
