### ISSUE TITLE
Incremental bullets don't increment in the audience view

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#564]
When you use incremental bullets, they increment properly in the Presenter view and the Display view, but not in the Audience view.

Thanks for pointing it out, @rnelson0

**Comment by ilavender** [comment]
were you able to locate the problem?

I see that li elements stay with class="incremental hidden" while in presenter view it changes to class="incremental"

looks like neither showoff:next or showoff:incr are being called in audience view
