### ISSUE TITLE
Do we really need a library to manage a string?

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#594]
This looks like way overkill.

https://github.com/puppetlabs/showoff/blob/master/public/js/showoff.js#L1300

Do we really need a complete library that's unmaintained and diverged from upstream just to trim a string to a length?

(library is https://github.com/smparkes/jquery.print/blob/master/src/jquery.print.js, btw)

**Comment by marrero984** [comment]
Yes, this is JavaScript.  In fact, get me a library to manage that library!
