### ISSUE TITLE
Getting auto scaleable text working using BigText.js

### ISSUE THREAD

**Issue by slambert** [binford2k/showoff#608]
This javascript library https://github.com/zachleat/BigText calculates the width of a line of text and scales text accordingly. (See this demo to get the idea: https://zachleat.github.io/BigText/demo/wizard.html) 

Really having trouble implementing this. Just to get it going, I am using `$('#h1').bigtext();` to try to catch all h1 headers in the slide. Tried it both inline like so:

    !SLIDE

    # HELLO HELLO HELLO

    <script>
    $('#h1').bigtext();
    </script>

And by putting the javascript in a .js file in the directory of the slideshow. No luck, can't get it to fire. Any ideas?

Why is this important? Personally, my style of slideshow has lots of one word, or one sentence slides in big text. This means a slideshow template can have the largest text possible for each "headline" on the slide.

**Comment by binford2k** [comment]
Bigtext doesn't work on individual elements, it works on containers of elements. (a div, p, ol, li, etc)

Here are a few things that work, play with them and see what works best.

Everything:

```javascript
$('.content').bigtext()`
```

Only headers:

```javascript
$('.content').bigtext({
    childSelector: '> h1'
})
```

A slide with a specific title:

```javascript
$('#Introduction_Section').bigtext()
```

Only slides marked with a specific class (e.g. `<!SLIDE bigly>`):

```javascript
$('.bigly').bigtext()
````

I'm not closing this ticket yet, because I think I might experiment with incorporating this library into core to support specifically the use case you describe.

**Comment by slambert** [comment]
Exciting - when do you expect to update the gem?

**Comment by binford2k** [comment]
@slambert Just did!

**Comment by slambert** [comment]
I added some padding so it wouldn't run the text _right_ to the edge of the screen. (It's the designer in me) Maybe you want to include it?

    .slide .bigtext {
         padding: 2vw;
     }

By the way, working on a template for multiple slideshows I do as a teacher with an org. Looking forward to posting it as an example. May have a few more issues come up in the meantime – hopefully useful to as many others as possible. But thanks for being so responsive!

**Comment by slambert** [comment]
Also, trying to center my content on the page (top to bottom) using this:

    div.content.bigtext {
        position: fixed;
        top: 50%;
        left: 50%;
        -webkit-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
    }

But then bigtext stops working. Maybe there's a better way?

Most of the time having the content centered (top/bottom) is what I'm looking for. I thought I could make a slide style, like <!SLIDE bigtext deadcenter> and then create some css like above for `div.deadcenter`...

**Comment by slambert** [comment]
Just found this on StackExchange, which appears to work better

    div.content.bigtext {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        display: flex;
        justify-content: space-around;
        align-items: center;
        flex-wrap: wrap;
    }

**Comment by slambert** [comment]
Grr, just noticed that css I posted messes with the line height when using multiple lines of text... back to the drawing board...

**Comment by slambert** [comment]
Ok, sorry to post so many messages, but I believe I figured it out:

This centers everything:

    div.content {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
    }

This centers just the bigtext stuff

    div.content.bigtext {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
    }

And if you have more than one line on the page, it should look correct.

Do with this what you like @binford2k! Hopefully it's useful. It'll definitely be a part of the slideshow I'm building...

**Comment by binford2k** [comment]
Thank you! Do you find that to display properly on IE?

**Comment by slambert** [comment]
Ha, I'm terrible when it comes to that – not something I've tested for in years!

I don't have a machine I can test it with either, so maybe someone reading this can jump in and help out?
