### ISSUE TITLE
background-fit images don't appear in presenter view thumbnail rollovers

### ISSUE THREAD

**Issue by slambert** [binford2k/showoff#635]
I am using a series of slides that are only images using background-fit. When hovering over the slides in presenter view, no image appears. See example below.

![no background-fit image-1](https://cloud.githubusercontent.com/assets/67271/21694345/b939b012-d352-11e6-8684-29a232cf034e.jpg)

**Comment by binford2k** [comment]
Hmm. Because this is a slide style, this is going to require duplicating the styles for the hover. Totally doable, but it might take a little though.

**Comment by slambert** [comment]
Re: duplicating the styles - hmmm, would that make what I mentioned [here](https://github.com/puppetlabs/showoff/issues/623#issuecomment-270732788) possible?
