### ISSUE TITLE
Hide address bar on mobile

### ISSUE THREAD

**Issue by raphink** [binford2k/showoff#659]
In order to gain some space in the presenter, it would be great if the address bar could be hidden on mobile devices.

**Comment by binford2k** [comment]
That would be awesome. Unfortunately, there's not a reliable way to do that on all platforms. See http://caniuse.com/#feat=fullscreen

The only way to do this reliably is to treat it as an application. But that requires the user to "install" it to their home screen, and we cannot do that without a consistent address, which we rarely have.

@marrero984 is working on a UI revamp that will include a fresh look at what a remote control view of the presenter would look like. He'll only display elements useful for that usage. Notes will be front and center and the slide preview might not even make an appearance. If you've got feedback on what would be useful, you should let us know.
