### ISSUE TITLE
layout issue with topbar buttons

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#696]
The annotations button is bigger than the topbar. I'll post a screenshot when the internet works again.

**Comment by binford2k** [comment]
![screen shot 2017-02-28 at 11 12 07 am](https://cloud.githubusercontent.com/assets/1392917/23441579/f11108d2-fdd7-11e6-82de-11bf0fed74be.png)

**Comment by marrero984** [comment]
Goddammit. It's not bigger, but JQuery-UI is adding a margin above it to hide the checkbox.  I had added a negative margin to counter, but apparently, it's not working all the time
