### ISSUE TITLE
Let users notify that they are done

### ISSUE THREAD

**Issue by raphink** [binford2k/showoff#700]
On exercise slides, it would be useful if users/students could notify that they are done with the exercise so the presenter can know and proceed.

**Comment by binford2k** [comment]
I'm also already working on exactly this functionality. It should be out soon.

**Comment by raphink** [comment]
Great ! Looking forward so I can stop asking my students if they're done every 5 minutes !

**Comment by raphink** [comment]
@marrero984 so you add a form ?

**Comment by raphink** [comment]
@marrero984 it actually does make sense to add a few questions after the exercise anyway.
