### ISSUE TITLE
add "ready check" feature 

### ISSUE THREAD

**Issue by fvoges** [binford2k/showoff#741]
In our trainings, when we have the labs, there's no way to find out wether the delegates have finished the exercises/labs or not. The only way to find out is to keep asking. 

As a presenter, I'd like to be able to do a "ready check". This could be a tag on the slide itself or a button that I can press on the presenter view to trigger the check.

At a minimum, it should show a yes/no pop-up to the viewers and show me the number of yes, no and pending answers.

**Comment by binford2k** [comment]
Already implemented as an `activity` tag. We'll roll it out in our classrooms in the next few weeks.
