### ISSUE TITLE
I would like to add logo as footer on each slide, troubles with subsection slide

### ISSUE THREAD

**Issue by tomthetrainer** [binford2k/showoff#772]
I wanted to put a logo at the base of each page. 

I added this to my css and it worked for all pages except subsection. 

```
.content::after {
  position: absolute;
  left: 1px;
  bottom: 1px;
  content: url(resources/my_logo.png);
  }
```

That works for all regular slides. 

If I center a slide

```!SLIDE center```

The logo is then superimposed on the slide content as the logo is centered as well. 

Is there a way to have a footer image that is not centered when the main slide content is centered

**Comment by samuelson** [comment]
@tomthetrainer this isn't exactly what you're looking for but it might work.  You can set a custom background. If you increase the size of the background for your logo image that might work. https://github.com/puppetlabs/showoff/blob/master/documentation/AUTHORING.rdoc#slide-backgrounds

The "center" class is a bit of a blunt instrument, unfortunately. Another option would be make your selector more specific so that it excludes the center class.

**Comment by tomthetrainer** [comment]
Thanks, 

I will take a look.

My question was rather basic, I doubt an issue is the most appropriate place for these discussions. 

Is there an email list, or a gitter chat room or something similar where I can ask basic advice, or see more user examples.

**Comment by samuelson** [comment]
It's ok, and I think it's a valid "issue" because at very least it needs to be documented. We don't have another public venue for support at the moment.

**Comment by tomthetrainer** [comment]
For anyone wanting to apply CSS to all slides but not the centered slides.

This seems to work. 


.content:not(.center)::after{
  position: absolute;
  left: 1px;
  bottom: 1px;
  content: url(resources/skymind_medium.png);
}

**Comment by samuelson** [comment]
Excellent! Thanks for posting the result. I hadn't seen the not() selector before, that looks really handy.

**Comment by binford2k** [comment]
An easier way to accomplish this might be to simply assign a background to the slide element. It positions the logo precisely on every slide, including the centered ones: 

```css
.slide {
  background: url(_images/logo.png) bottom left no-repeat;
}
```

If you'd rather that it didn't show up on the subsections, just add:

```css
.slide.subsection {
  background: none;
}
```

You could also make rules for `.cover` or `.center`, etc.
