### ISSUE TITLE
Rendering issues on chrome/firefox in linux

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#776]
## Missing buttons
* In firefox browser on Linux when running the presenter view, the buttons at the top of the screen for report issue with slide, display window, etc load and then vanish instantly – solution, use chromium or alternate browser
* In chromium browser on Linux, the new checkbox for "exercise complete" is not visible at all – solution, use firefox or alternate browser

## Impact
Both bugs manifest at the same time for me, which means I need to run my presenter window in chromium and my display window in firefox - otherwise no buttons

reported by @GeoffWilliams

**Comment by marrero984** [comment]
@GeoffWilliams What versions of FireFox and Chromium are you using?

**Comment by binford2k** [comment]
The issue with Firefox seems to be an actual Firefox issue. You know that notification bar that shows up on the bottom of the window sometimes? I notice that the presenter window (100% of the viewport height) shifts up by exactly that amount on the first load and only when you have to log in. If you hit reload after logging in, it works just fine.

**Comment by binford2k** [comment]
I take it back. On Linux only (centos7) I'm able to consistently make both Firefox and Chrome push up off the top of the screen when the screen resolution is on the small side.

@GeoffWilliams, what's your screen resolution?

**Comment by GeoffWilliams** [comment]
@binford2k apologies for delay in getting back to you - info as requested and found a partial workaround:

## Chromium

![screenshot_2017-06-20_21-57-47](https://user-images.githubusercontent.com/3904115/27332034-8a28a7f4-5603-11e7-9dee-d982a54e3dc0.png)
After updating gems, the presenter options are visible...

![screenshot_2017-06-20_21-58-58](https://user-images.githubusercontent.com/3904115/27332064-b0353296-5603-11e7-9a20-08c8de88bdee.png)
...but use :arrow_left: or :arrow_right: and it vanishes

![screenshot_2017-06-20_22-03-21](https://user-images.githubusercontent.com/3904115/27332205-507c9442-5604-11e7-989d-518785c06159.png)
...no checkbox for lab complete so follow mode stops

## Firefox
![screenshot_2017-06-20_22-07-03](https://user-images.githubusercontent.com/3904115/27332354-dbb4b9ae-5604-11e7-92d3-79d5d10b13c5.png)
Menu bar vanishes as soon as the page loads in firefox

![screenshot_2017-06-20_22-09-05](https://user-images.githubusercontent.com/3904115/27332408-1c5b7d30-5605-11e7-80f2-25b75ba9ce0d.png)
...but the activity complete checkbox is shown

## Version info
```
$ dpkg -l chromium-browser firefox
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  chromium-brows 58.0.3029.11 amd64        Chromium web browser, open-source
ii  firefox        54.0+build3- amd64        Safe and easy web browser from Mo

$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

```

## Screen info
```
$ xrandr -q
Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 16384 x 16384
eDP-1-1 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 310mm x 174mm
```

## Workaround (presenter)
Your note on resolutions is the clue to fix this - `ctrl`+`alt`+`-` zoom to 90% fixes the presenter in both browsers

## No workaround (missing checkbox)
Zoom in/out makes no difference to the missing checkbox on chromium - page doesn not resize with zoom hotkeys, it just jumps around a bit

**Comment by binford2k** [comment]
@GeoffWilliams thanks for the info. One thing I noticed was that it appears that you are opening a second window to put on the projector. **Don't do that**.

As a presenter, you should never see the *Activity Complete* checkbox. That only shows up for audience members. As a presenter, you should open the display view using the button and put that on the projector. That window is exempt from the checkbox and certain other audience interactivity features. When you open a second window manually, you're explicitly pretending to be an audience member instead of the presenter.

![27332034-8a28a7f4-5603-11e7-9dee-d982a54e3dc0](https://user-images.githubusercontent.com/1392917/27347001-d36a0ec2-55a3-11e7-862b-e41310a66b9f.png)

I'll look into the other issues now that I've got a few clues.

**Comment by GeoffWilliams** [comment]
No worries - @binford2k it is a display window in chromium - ~~I got it from clicking the button.~~ - and that is why there is no checkbox for activity complete.  In firefox I couldn't click it because it jumped out of the way too quickly.  Thanks

**Comment by binford2k** [comment]
@GeoffWilliams gotcha. That explains why you see the checkbox on Firefox, but not Chromium.

Ok, so what you're running into boils down to is two issues, correct me if I'm misreading this:

1. In Firefox, the menubar isn't usable.
1. In Chromium, follow mode stops on activities when it should not.

Thanks for the back & forth. That isolates some test cases that I can validate against.

**Comment by GeoffWilliams** [comment]
I've just triple checked this - I don't know if recent updates fixed the second issue but I'm no longer able to reproduce it.  We're left with:

1. On firefox, menubar is unusable immediately on page load
2. On chromium menubar is unusable after navigation :left_right_arrow: 

**Workaround**
3. On both browsers, the menubar can be coaxed back by zooming out. On chromium zoom <100 results in a permanent fix, zoom == 100 gives a temporary fix that is lost on :left_right_arrow:

**Comment by binford2k** [comment]
@GeoffWilliams hey, got it tracked down. What a PITA. As a short term mitigation, clicking the menu button to hide the navigation menu **prior to** navigation will keep the menu from disappearing.
