### ISSUE TITLE
When browsing the presenter view in Firefox, the screen doesn't show below the slide view

### ISSUE THREAD

**Issue by JonTheNiceGuy** [binford2k/showoff#79]
On my Firefox browser, the notes area, the "Update followers" button, the "enable remote" and zoom slider don't exist.
![how the internet works - mozilla firefox_003](https://f.cloud.github.com/assets/228671/1301691/513bd084-3126-11e3-964d-c495f6ad88d6.png)

Note, however, that it does work with Rekonq (the default browser for KDE based distributions) and Chromium
![how the internet works - rekonq_001](https://f.cloud.github.com/assets/228671/1301692/513d6c5a-3126-11e3-877a-707e9c2080d7.png)
![how the internet works - chromium_002](https://f.cloud.github.com/assets/228671/1301690/513aedc2-3126-11e3-9503-3f85caefb382.png)

**Comment by binford2k** [comment]
The presenter rendering has been greatly improved on firefox
