### ISSUE TITLE
Clarify the answer key

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#795]
Clarify the answer key introduced in https://github.com/puppetlabs/showoff/pull/767

**Comment by marrero984** [comment]
Is it trying to convey too much info?  Should we reduce it to just showing what the student got correct and incorrect or what the correct answers are?

Another possibility is a key/legend for students and teachers

**Comment by binford2k** [comment]
What would said legend look like?

* ~Strikethrough~: This **option** is incorrect
* Red: You **answered** this question incorrectly by selecting this option

Maybe we should move the red/green messaging to the question itself, rather than any of the options?
