### ISSUE TITLE
Need the ability to exclude a section from the validator

### ISSUE THREAD

**Issue by trevor-vaughan** [binford2k/showoff#810]
Sometimes I want the format for consistency but I know that the validator is going to have a fit.

**Comment by binford2k** [comment]
Using a tag of `no-validate` alongside the language should do that, if I'm understanding you right. https://puppetlabs.github.io/showoff/documentation/PRESENTATION_rdoc.html#label-In-slide+code+validation+scripts

(the docs could use some reorganization to make this easier to find, for sure.)

**Comment by trevor-vaughan** [comment]
@binford2k I'll try that. Heh...
