### ISSUE TITLE
Question: Is is possible to use the 'center' slide class but keep the first 'h1' at the top?

### ISSUE THREAD

**Issue by trevor-vaughan** [binford2k/showoff#812]
I'm trying to create some slides where the content is centered but I still have a consistent header.

Is this possible?

Thanks

**Comment by binford2k** [comment]
i.e., the header is in the same place as every other slide, but the content itself is vertically & horizontally centered?

That would take custom styles right now, though that look is something we've talked about a bit.

**Comment by trevor-vaughan** [comment]
Yeah, that's what I'm looking for.

Having an optional consistent header and footer that could be toggled per slide would be awesome.

Closing this as "can't do it yet".
