### ISSUE TITLE
AutoPlay slides, not just preshow images

### ISSUE THREAD

**Issue by tomthetrainer** [binford2k/showoff#829]
I use showoff for my training content, but I would also like to play a series of slides automatically. 

Is there a way to do this? 

Can I modify the .json or the css in some way to build a deck that plays each slide for a specific time and then moves to next and loops?

Thanks

**Comment by tomthetrainer** [comment]
Perhaps I can add or modify some javascript to make a call to NEXT,

**Comment by binford2k** [comment]
I can't promise a timeline on it, but we have some experimental side projects experimenting with exactly this idea. In the meantime, you could certainly some variation of:

    setInterval(nextStep, 3000);

Just drop that into a javascript file (with a `.js` extension) into the root of your presentation next to the `showoff.json` file.

**Comment by tomthetrainer** [comment]
@binford2k Thanks that gets me through one loop, 

Please be patient with me my javascript skills are weak. 

How would I get it to loop back to the beginning ?

Looking at the JS_API file it seems I can  
getSlideProgress() and when that hits the end I can gotoSlide(num)

Or is there another way?

getSlideProgress() - returns string '5/18'
getCurrentNotesText() - returns string of current notes
getCurrentNotes() - returns HTMLElement of current notes
gotoSlide(num)
getSlidePercent() - returns int
prevStep()
nextStep()
toggleFooter()
togglePreshow()
executeAnyCode()

**Comment by binford2k** [comment]
Ah, sorry. I forgot about that part :)

    setInterval(function() {
        if(nextStep() == undefined) { 
            gotoSlide(0);
        }
    }, 3000);

**Comment by tomthetrainer** [comment]
Hah perfect !! I was about to hack it in some functional but unattractive manner. I assume that what you show will work, let me test, and then verify and close the issue. Is there a place to post these little useful hacks? Or just leave them in the issues?

**Comment by binford2k** [comment]
I should set up something like that. Thanks for the idea!

For this particular issue, here is fine. I'm planning to add some keywords to codify it a little more so you don't need the js hack to do it. But there's certainly going to be some things that need custom code written.

**Comment by tomthetrainer** [comment]
@binford2k Thanks for your help, 

That will work for my purposes, 

Note that a slide with a transition 
```<!SLIDE bullets incremental transition=fade>```

Seems to return "undefined" for nextStep() and therefore sends back to top

Not an issue for me, and probably a few characters changed in the Javascript would workaround that, 

Just leaving that as a note for anyone who wants to use this later, if I need to workaround that I will update the javascript here. 

Thanks again.
