### ISSUE TITLE
logitech remotes no longer work

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#862]
The PR in #842 switched PageUp/Down to navigate by section instead of slides. That's an awesome feature, but it turns out that most Logitech remotes send those keys for prev/next, so we've just bumped off a large number of users.

Keyboard shortcuts for the major slideshow tools:

* [Keynote](https://support.apple.com/kb/PH24313?viewlocale=en_US&locale=en_US)
    * Up/Down
    * Right/Left
* [Powerpoint](https://support.office.com/en-us/article/use-keyboard-shortcuts-to-deliver-your-presentation-1524ffce-bd2a-45f4-9a7f-f18b992b93a0)
    * Up/Down
    * Right/Left
    * PageUp/PageDown
    * N/P
    * Space/Backspace
* [Openoffice](https://wiki.openoffice.org/wiki/Documentation/OOoAuthors_User_Manual/Impress_Guide/Shortcut_keys_in_slide_shows)
    * Up/Down
    * Right/Left
    * PageUp/PageDown
    * N/P
    * Enter/Backspace
    * Space/Backspace
* [Google](https://support.google.com/docs/answer/1696717?co=GENIE.Platform%3DDesktop&hl=en)
    * Up/Down
    * PageUp/PageDown
* [Showoff](https://puppetlabs.github.io/showoff/documentation/CONFIGURATION_rdoc.html)
    * Up/Down
    * Right/Left
    * Move by section: PageUp/PageDown

**Comment by binford2k** [comment]
@raphink hey, question for you. When you use the PageUp/PageDown controls, are you at the keyboard or are you using a remote? (if remote, which one?)

**Comment by raphink** [comment]
I'm using the keyboard. I don't mind changing this, but it's a shame that all these software are squatting multiple keybindings ;-)

**Comment by jessereynolds** [comment]
I'm in favour of reverting this behavior (backing out PR #842) as it's a significant change to the trusted and relied upon behaviour of showoff with logitech clickers. 

Maybe add a modifier key for next section, eg control+page down?

**Comment by fvoges** [comment]
Most remotes are setup to use page up/down because powerpoint uses that. And the keystrokes the send are not configurable
