### ISSUE TITLE
In forms, free text input triggers presentation shortcuts

### ISSUE THREAD

**Issue by gerapeldoorn** [binford2k/showoff#863]
When I use forms, the user input on the text Fields trigger shortcuts.

Example:
-  a student is filling out a form in the presentation. There is an open text field in the user tries to input some text there.

 Expected result:
- the user is able to enter a sentence a an answer to an open question

 Actual result:
- shortcut keys are triggered. The first letter of 'pufferfish' would pause the screen.

 This does not happen all the time, but I have seen it on Internet Explorer, Edge and Chrome on Windows. A reload of the page on the student's side usually fixes the issue.

 Showoff is version 1.19.3 and runs in a docker container.

Thanks!

**Comment by binford2k** [comment]
The root cause is the `.find` here. https://github.com/puppetlabs/showoff/blob/8c43b7c28f5d991ed3b79508af6e72acb44619f4/public/js/showoff.js#L724-L726

It's causing the IE js engine to have a kitten in unpredictable ways.
