### ISSUE TITLE
Font Awesome is outdated

### ISSUE THREAD

**Issue by gerapeldoorn** [binford2k/showoff#873]
An update would be much appreciated.

Alternatively, a way to upgrade locally (or use the online version by including the css) would be even better.

I've tried this in my css:
`@import url('https://use.fontawesome.com/releases/v5.2.0/css/all.css');`

but it has no effect.

Thanks!

**Comment by binford2k** [comment]
FWIW, while investigating this issue and prior to any Showoff updates, I added this line to the top of a custom css file:

```css
@import url('https://use.fontawesome.com/releases/v5.6.1/css/all.css');
```

and then this HTML displayed properly.

```html
<i class="fa fa-candy-cane"></i> This should show a candy cane!
```

Did you fully reload the browser to ensure that all CSS files were loaded in?
