### ISSUE TITLE
PDF generation doesn't work

### ISSUE THREAD

**Issue by fabioperrella** [binford2k/showoff#880]
Hi!

I've tried to generate a PDF from my presentation by I couldn't.

Here it is the output:
```
$ bundle exec showoff pdf output.pdf
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
... # this message repeated a lot of times
```

The pdf was generated but incorrectly.

![image](https://user-images.githubusercontent.com/302303/49839367-e8a6cc80-fd95-11e8-8ecd-20f5def93cf2.png)

There is only 1 page, but my presentation has 30 slides.

You can download my presentation and simulate the problem in https://github.com/fabioperrella/debugging-with-mastery

**Comment by binford2k** [comment]
Thanks for the report! Your presentation appears to generate properly now.
