### ISSUE TITLE
Permission Denied error occurred when I'm trying to translate it into Chinese.

### ISSUE THREAD

**Issue by MinboGaoTHU** [binford2k/showoff#917]
## Detailed description of the situation I met.
The showoff project is attracting and I'm trying to use it on my Windows computer. For simplicity, I installed Ruby using WSL (Windows Subsystem for Linux), Ubuntu. 
For the first time I use, the translation problem occurred: it can't load Chinese since there is no such translation. So I tried to translate the en.yml into zh.yml in my Windows directory, but when I type "showoff server" in the bash, the following error message occurred:

```
Traceback (most recent call last):
        16: from /home/luoling/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
        15: from /home/luoling/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
        14: from /home/luoling/.rvm/gems/ruby-2.5.5/bin/showoff:23:in `<main>'
        13: from /home/luoling/.rvm/gems/ruby-2.5.5/bin/showoff:23:in `load'
        12: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/showoff-0.20.1/bin/showoff:4:in `<top (required)>'
        11: from /home/luoling/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from /home/luoling/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/showoff-0.20.1/lib/showoff.rb:31:in `<top (required)>'
         8: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/showoff-0.20.1/lib/showoff.rb:65:in `<class:ShowOff>'
         7: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/sinatra-1.4.8/lib/sinatra/base.rb:1411:in `configure'
         6: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/showoff-0.20.1/lib/showoff.rb:68:in `block in <class:ShowOff>'
         5: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/i18n-1.8.2/lib/i18n/backend/base.rb:18:in `load_translations'
         4: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/i18n-1.8.2/lib/i18n/backend/base.rb:18:in `each'
         3: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/i18n-1.8.2/lib/i18n/backend/base.rb:18:in `block in load_translations'
         2: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/i18n-1.8.2/lib/i18n/backend/base.rb:225:in `load_file'
         1: from /home/luoling/.rvm/gems/ruby-2.5.5/gems/i18n-1.8.2/lib/i18n/backend/base.rb:240:in `load_yml'
/home/luoling/.rvm/gems/ruby-2.5.5/gems/i18n-1.8.2/lib/i18n/backend/base.rb:244:in `rescue in load_yml': can not load translations from /home/luoling/.rvm/gems/ruby-2.5.5/gems/showoff-0.20.1/lib/../locales/zh.yml: #<Errno::EACCES: Permission denied @ rb_sysopen - /home/luoling/.rvm/gems/ruby-2.5.5/gems/showoff-0.20.1/lib/../locales/zh.yml> (I18n::InvalidLocaleData)
```

## Suggestions
I'm new to Ruby, but I really find this project interesting. (And I want to use it). So how can the above problem be solved?(I already translate the yml file and have one in my own computer.)
By the way, I think maybe the following feature can be added: if there is no translation currently, then set the default display language into English, so that there won't be some translation loading errors.

Thank you very much!

**Comment by binford2k** [comment]
what happens if you run `type locales/zh.yml` from the root of the repository as the same user you're trying to run showoff as? And did you install as the same user?

Also, using PowerShell, what does `Dir | Get-Acl` show from inside the `home/luoling/.rvm/gems/ruby-2.5.5/gems/showoff-0.20.1/locales` directory?

**Comment by MinboGaoTHU** [comment]
Thank you very much for the guidance. I've fixed the problem by noticing that I've made a big mistake when I was using WSL system. The yml file can't be opened in that way.
