### ISSUE TITLE
Images are not shown using serve

### ISSUE THREAD

**Issue by CircleCode** [binford2k/showoff#928]
## Describe the Bug
Running `showoff serve` in the ./example directory builds and serves the presentation.
However, images are not displayed.
For example, octocat from `./example/one/slidesA.md#50` is looked from `http://localhost:9090/image/one/octocat.png` and triggers a 404 error

## Expected Behavior
images are shown

## Steps to Reproduce
1. `cd ./example`
2. `showoff serve`
3. open http://localhost:9090/presenter#7

## Environment
 - showoff version 0.20.3
 - ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
 - Platform arch linux

## Additional Context
- Note: showoff static works (but images are then located at `/file/…`)

**Comment by CircleCode** [comment]
Note: the same behaviour is observed with `binford2k/showoff` docker image:

1. `cd /tmp`
2. `git clone https://github.com/puppetlabs/showoff.git`
3. `docker run -p 9090:9090 -v /tmp/showoff/example:/var/cache/showoff binford2k/showoff`

**Comment by xiongchiamiov** [comment]
I was trying to figure out how to embed images, since it wasn't working and that's not actually covered in the documentation anywhere.  Surprise! I guess I was actually guessing at it correctly and it just isn't working.

**Comment by werebus** [comment]
This bug was introduced on Showoff 0.20.3 and is due to its dependency on Sinatra being bumped to 2.x.

In Sinatra 2.x, the regexp-based route matching was fixed to require a match to the full path.

**Comment by silug** [comment]
> This bug was introduced on Showoff 0.20.3 and is due to its dependency on Sinatra being bumped to 2.x.
> 
> In Sinatra 2.x, the regexp-based route matching was fixed to require a match to the full path.

I can confirm that using a `Gemfile` with
```ruby
gem 'showoff', '0.20.2'
gem 'sinatra', '~> 1'
```
works around the issue.
